In [99]:
with open("input.txt", "r", encoding = 'utf-8') as f:
    text = f.read()

In [100]:
print("length of the dataset: " + str(len(text)))
print(text[:99])

length of the dataset: 1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
Yo


In [101]:
chars = list(set(text))
print(chars)
print(len(chars))
vocab_size = len(chars)

['p', 'T', 'J', 'c', 'i', ' ', 'B', 'O', 'U', 'G', 'Z', 'z', 'Q', 'h', '!', 'e', 'N', 'u', ';', 'g', '?', 'Y', 'j', 'q', 'R', 'x', 'I', 'n', 'K', 'o', '.', 'm', 'S', '-', 'W', 'y', 's', 'H', 'C', 'L', 'a', ',', 'k', '3', 'r', 'E', ':', '\n', 'F', "'", 'V', 'A', 't', 'w', 'b', 'D', 'X', 'P', '$', 'f', 'l', 'v', 'M', '&', 'd']
65


In [102]:
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[ch] for ch in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [103]:
print(stoi)
print(itos)
print(encode("Hello World"))

{'p': 0, 'T': 1, 'J': 2, 'c': 3, 'i': 4, ' ': 5, 'B': 6, 'O': 7, 'U': 8, 'G': 9, 'Z': 10, 'z': 11, 'Q': 12, 'h': 13, '!': 14, 'e': 15, 'N': 16, 'u': 17, ';': 18, 'g': 19, '?': 20, 'Y': 21, 'j': 22, 'q': 23, 'R': 24, 'x': 25, 'I': 26, 'n': 27, 'K': 28, 'o': 29, '.': 30, 'm': 31, 'S': 32, '-': 33, 'W': 34, 'y': 35, 's': 36, 'H': 37, 'C': 38, 'L': 39, 'a': 40, ',': 41, 'k': 42, '3': 43, 'r': 44, 'E': 45, ':': 46, '\n': 47, 'F': 48, "'": 49, 'V': 50, 'A': 51, 't': 52, 'w': 53, 'b': 54, 'D': 55, 'X': 56, 'P': 57, '$': 58, 'f': 59, 'l': 60, 'v': 61, 'M': 62, '&': 63, 'd': 64}
{0: 'p', 1: 'T', 2: 'J', 3: 'c', 4: 'i', 5: ' ', 6: 'B', 7: 'O', 8: 'U', 9: 'G', 10: 'Z', 11: 'z', 12: 'Q', 13: 'h', 14: '!', 15: 'e', 16: 'N', 17: 'u', 18: ';', 19: 'g', 20: '?', 21: 'Y', 22: 'j', 23: 'q', 24: 'R', 25: 'x', 26: 'I', 27: 'n', 28: 'K', 29: 'o', 30: '.', 31: 'm', 32: 'S', 33: '-', 34: 'W', 35: 'y', 36: 's', 37: 'H', 38: 'C', 39: 'L', 40: 'a', 41: ',', 42: 'k', 43: '3', 44: 'r', 45: 'E', 46: ':', 47: '\n',

In [104]:
print(decode([60, 26, 57, 57, 15, 31, 3, 15, 4, 57, 55]))

lIPPemceiPD


In [105]:
import torch

data = torch.tensor(encode(text), dtype= torch.long)
print(data.shape, data.dtype)
print(data[:99])

torch.Size([1115394]) torch.int64
tensor([48,  4, 44, 36, 52,  5, 38,  4, 52,  4, 11, 15, 27, 46, 47,  6, 15, 59,
        29, 44, 15,  5, 53, 15,  5,  0, 44, 29,  3, 15, 15, 64,  5, 40, 27, 35,
         5, 59, 17, 44, 52, 13, 15, 44, 41,  5, 13, 15, 40, 44,  5, 31, 15,  5,
        36,  0, 15, 40, 42, 30, 47, 47, 51, 60, 60, 46, 47, 32,  0, 15, 40, 42,
        41,  5, 36,  0, 15, 40, 42, 30, 47, 47, 48,  4, 44, 36, 52,  5, 38,  4,
        52,  4, 11, 15, 27, 46, 47, 21, 29])


In [106]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [107]:
block_size = 8

In [108]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(x,y)
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target is {target}")


tensor([48,  4, 44, 36, 52,  5, 38,  4]) tensor([ 4, 44, 36, 52,  5, 38,  4, 52])
when input is tensor([48]) the target is 4
when input is tensor([48,  4]) the target is 44
when input is tensor([48,  4, 44]) the target is 36
when input is tensor([48,  4, 44, 36]) the target is 52
when input is tensor([48,  4, 44, 36, 52]) the target is 5
when input is tensor([48,  4, 44, 36, 52,  5]) the target is 38
when input is tensor([48,  4, 44, 36, 52,  5, 38]) the target is 4
when input is tensor([48,  4, 44, 36, 52,  5, 38,  4]) the target is 52


In [109]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

In [110]:
xb,yb = get_batch("train")
print("inputs: ")
print(xb.shape)
print(xb)
print("targets: ")
print(yb.shape)
print(yb)

inputs: 
torch.Size([4, 8])
tensor([[39, 15, 52, 49, 36,  5, 13, 15],
        [59, 29, 44,  5, 52, 13, 40, 52],
        [27, 52,  5, 52, 13, 40, 52,  5],
        [62, 45,  7, 46, 47, 26,  5,  0]])
targets: 
torch.Size([4, 8])
tensor([[15, 52, 49, 36,  5, 13, 15, 40],
        [29, 44,  5, 52, 13, 40, 52,  5],
        [52,  5, 52, 13, 40, 52,  5, 13],
        [45,  7, 46, 47, 26,  5,  0, 40]])


In [111]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    def forward(self, idx,targets = None):
        logits = self.token_embedding_table(idx)
        if targets is None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits,targets)
        return logits,loss
    def generate(self,idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
m = BigramLanguageModel(vocab_size)
logits,loss = m(xb,yb)
print(logits.shape)
print(loss)

idx = torch.zeros((1,1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens = 100)[0].tolist()))

torch.Size([32, 65])
tensor(4.5404, grad_fn=<NllLossBackward0>)
pmqY,RSzh,uRxwSalClTeQtDOouGGZejD'nq?ODzZVLJw
&v'?FEe:daoQfJGaRYEv3lA&;jg-gbpvtHyAtMqyy3lO$NDsuXWqREj


In [112]:
optimizer = torch.optim.AdamW(m.parameters(), lr = 1e-3)

In [113]:
batch_size = 32
for steps in range(10000):
    xb,yb = get_batch('train')

    logits, loss = m(xb,yb)
    optimizer.zero_grad(set_to_none = True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.372959852218628


In [114]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))       

pe w ata tuio nefofer AEm, MAnd Ond sonfonearorave lantofouce ge saysthethes igat beo JUqut stalfr my, wse l,
Whar:


m RTo nt, d other y Tethir itou byorl nines has t:
Be n; I'stco withst thours ns ll chimus d tok!


NEThaitferg apinowe hiforeinomirpwindord dinyorale strvellye, n the ade llors day, by areflithanelor Kit d sof e llld rcah, y him h d ha crethou, th. y.
There grsuto br oo t 'lmeretham.
Duecthe'sseshit fof he he-
Th, he thave.

Aroungm f, d's oan.
PETUCandorn.
The t t deine INTheris


In [119]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [120]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev, 0)

In [121]:
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow,xbow2)

False

In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias = False)
query = nn.Linear(C, head_size, bias = False)

tril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim = -1)
xbow3 = wei @ x
torch.allclose(xbow,xbow3)

False

In [124]:
print(xbow[1],xbow2[1])

tensor([[ 1.3488, -0.1396],
        [ 0.8173,  0.4127],
        [-0.1342,  0.4395],
        [ 0.2711,  0.4774],
        [ 0.2421,  0.0694],
        [ 0.0084,  0.0020],
        [ 0.0712, -0.1128],
        [ 0.2527,  0.2149]]) tensor([[ 1.3488, -0.1396],
        [ 0.8173,  0.4127],
        [-0.1342,  0.4395],
        [ 0.2711,  0.4774],
        [ 0.2421,  0.0694],
        [ 0.0084,  0.0020],
        [ 0.0712, -0.1128],
        [ 0.2527,  0.2149]])


In [118]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('----')
print('b=')
print(b)
print('----')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
----
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
----
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
